### ISSUE TITLE
Alternative criteria for getting the crown

### ISSUE THREAD

**Issue by ChloeIsNobody** [thecolonel63/technomodel#2]
just a suggestion, but maybe it would be a cool idea to add a few more situations to give the pig a crown? For example: making the name case-sensitive, making the name only need to contain the string "technoblade" instead of being entirely composed of it, and adding a few more strings like "the blade", "techno", or "technothepig"
I also think it could be a neat idea to make the crown appear for all pigs with the tag {Invulnerable:1b}, or maybe even appear randomly for naturally spawning pigs. However, these last two may not be ideal for some people so it might be good to allow them to be disabled in config.
These are just a few ideas I had to make the mod more interesting, I understand if you don't want to add them.
Have a nice day!

**Comment by ChloeIsNobody** [comment]
also to add on to the idea of naturally spawning pigs getting the techno crown, I'd imagine it would be pretty rare, but you could make a reference out of the number. For example, you could make it spawn at a chance of 1/500 (in refrence to the 500 million potatoes techno farmed to win the potato war) or maybe 1/1400 or 1/1818 (in reference to the bedwars winstreaks). Again, just a few more suggestions, no pressure to add anything you don't want to.
Oh also new splash text might be cool to add.

**Comment by thecolonel63** [comment]
These are very interesting ideas to add, however I believe the current system of naming it "Technoblade" reflects best on how Minecraft naturally handles special nametag scenarios, those only including the one, case-sensitive string.

In addition, adding the other features you mentioned would require access to the server end, which would mean the mod would only work in singleplayer, and would no longer be backwards compatible with 1.18 and below.

Still though, excellent suggestions, have a nice day.

**Comment by ChloeIsNobody** [comment]
alright, that's fair enough. Although for the spawn chance thing I was thinking you could do something similar to optifine's random entity textures and the entity texture features mod so you wouldn't need the mod to be server-side.
I still maintain that adding a new splash text or two would be cool, but it's your mod not mine haha.
Thank you for your response, and good luck with whatever you decide to do with this mod in the future!
