### ISSUE TITLE
Hope you can make the pig named "Technoblade" undying

### ISSUE THREAD

**Issue by ChocomintTW** [thecolonel63/technomodel#4]

**Comment by thecolonel63** [comment]
I'm sorry, but this would require access to the server side, which is not possible on a mod designed to work purely on the client end.

You can, however, achieve a similar effect by putting the command "/execute as @e[type=pig,name=Technoblade] run data merge entity @s {Invulnerable:1}" into either a repeating command block or a datapack; any place which would run the command constantly.
